// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWUM6F3cUM8FrtpgTAzofNvBNrk178uvA',
    appId: '1:686810964141:web:3411b861e42c90faf62624',
    messagingSenderId: '686810964141',
    projectId: 'mymeds-application-f99dd',
    authDomain: 'mymeds-application-f99dd.firebaseapp.com',
    storageBucket: 'mymeds-application-f99dd.firebasestorage.app',
    measurementId: 'G-NJ4KEPYSGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW4zpIytCaCMdCiCC4FaB1zWLzjzUzrIo',
    appId: '1:686810964141:android:160b991829d89700f62624',
    messagingSenderId: '686810964141',
    projectId: 'mymeds-application-f99dd',
    storageBucket: 'mymeds-application-f99dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF_pJbL_DY_GqhNNWPEcwndeSY9ICkBQ4',
    appId: '1:686810964141:ios:5c0ba234dfa5a674f62624',
    messagingSenderId: '686810964141',
    projectId: 'mymeds-application-f99dd',
    storageBucket: 'mymeds-application-f99dd.firebasestorage.app',
    iosBundleId: 'com.example.mymeds',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF_pJbL_DY_GqhNNWPEcwndeSY9ICkBQ4',
    appId: '1:686810964141:ios:5c0ba234dfa5a674f62624',
    messagingSenderId: '686810964141',
    projectId: 'mymeds-application-f99dd',
    storageBucket: 'mymeds-application-f99dd.firebasestorage.app',
    iosBundleId: 'com.example.mymeds',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWUM6F3cUM8FrtpgTAzofNvBNrk178uvA',
    appId: '1:686810964141:web:216e9acceecadc8ff62624',
    messagingSenderId: '686810964141',
    projectId: 'mymeds-application-f99dd',
    authDomain: 'mymeds-application-f99dd.firebaseapp.com',
    storageBucket: 'mymeds-application-f99dd.firebasestorage.app',
    measurementId: 'G-T8QKB16VTY',
  );
}
