import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'providers/system_conditions_provider.dart';
import 'widgets/low_battery_toast.dart';
import 'theme/app_theme.dart';
import 'routes/app_router.dart';
import 'services/user_session.dart';
import 'services/settings_service.dart';
import 'services/connectivity_service.dart';
import 'services/profile_cache_service.dart';
import 'services/profile_sync_service.dart';
import 'services/cache_service.dart';
import 'services/storage_service.dart';
import 'services/auth_service.dart';
import 'services/sync_queue_service.dart';
import 'services/orders_cache_service.dart';
import 'services/prescriptions_cache_service.dart';
import 'services/favorites_service.dart';
import 'services/lru_prescription_cache.dart';
import 'services/prescription_image_storage.dart';
import 'services/autofill_service.dart';
import 'services/prescription_draft_cache.dart';
import 'ui/auth/auth_wrapper.dart';
// import 'utils/firebase_seeder.dart'; //for seeding uncomment
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'providers/motion_provider.dart';
import 'providers/settings_provider.dart';
import 'providers/smart_notification_provider.dart';
import 'package:provider/provider.dart';
import 'ui/dialogs/mobile_data_prompt_dialog.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Hive for offline storage
  await Hive.initFlutter();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // 🌱 SEEDING: Uncomment to seed database (run once then comment out)
  //await FirebaseSeeder().seedAll();

  // Initialize storage service (must be before session restoration)
  await StorageService().init();

  // Initialize user session management
  await UserSession().init();

  // Attempt to restore session from local storage
  final hasValidSession = await AuthService.restoreSessionFromLocal();
  debugPrint('main: Session restoration result: $hasValidSession');

  // Initialize settings service
  await SettingsService().init();

  // Initialize connectivity service
  await ConnectivityService().init();

  // Initialize profile cache service
  await ProfileCacheService().init();

  // Initialize profile sync service
  final profileSyncService = ProfileSyncService();
  await profileSyncService.init(
    onSyncEvent: (event) async {
      debugPrint('📤 Sync Event: ${event.type} - ${event.message}');
      // You can handle sync events globally here if needed
    },
  );

  // Initialize cache service for background loading
  await CacheService().init(
    maxSize: 100,
    defaultTtl: const Duration(hours: 1),
  );

  // Initialize connectivity service
  await ConnectivityService().init();

  // Initialize sync queue service for eventual connectivity
  await SyncQueueService().init();
  
  // Initialize orders cache service for offline-first orders
  await OrdersCacheService().init();
  
  // Initialize prescriptions cache service for offline-first prescriptions
  await PrescriptionsCacheService().init();

  // Initialize favorites service for favorite pharmacies
  await FavoritesService().init();

  // Initialize LRU caches for pending prescription uploads
  NFCUploadCache().init(maxSize: 20);  // NFC uploads cache
  ImageUploadCache().init(maxSize: 50); // Image uploads cache

  // Initialize prescription image storage for offline image persistence
  await PrescriptionImageStorage().init();

  // Initialize autofill service for smart form suggestions
  await AutofillService().initialize();
  // Initialize prescription draft cache for saving work-in-progress prescriptions
  await PrescriptionDraftCache().init();

  // Initialize SettingsProvider
  final settingsProvider = SettingsProvider();
  await settingsProvider.init();

  // Initialize SmartNotificationProvider
  final smartNotificationProvider = SmartNotificationProvider();
  await smartNotificationProvider.initialize();

  runApp(
     MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) {
          final motionProvider = MotionProvider();
          motionProvider.start();
          return motionProvider;
        }),
        ChangeNotifierProvider(create: (_) => SystemConditionsProvider()),
        ChangeNotifierProvider(create: (_) => settingsProvider),
        ChangeNotifierProvider(create: (_) => smartNotificationProvider),
      ],
      child: const LowBatteryToast(
        child: MyMedsApp(),
      ),
    ),
  );
}

class MyMedsApp extends StatefulWidget {
  const MyMedsApp({super.key});

  @override
  State<MyMedsApp> createState() => _MyMedsAppState();
}

class _MyMedsAppState extends State<MyMedsApp> {
  late SettingsProvider _settingsProvider;
  bool _listenerSetup = false;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    
    // Set up listener on first build
    if (!_listenerSetup) {
      _setupMobileDataListener();
      _listenerSetup = true;
    }
  }

  /// Setup listener for mobile data detection
  void _setupMobileDataListener() {
    try {
      _settingsProvider = context.read<SettingsProvider>();
      debugPrint('🎯 Adding listener to SettingsProvider');
      _settingsProvider.addListener(_checkMobileDataPrompt);
      
      // Initial check
      debugPrint('🎯 Performing initial prompt check');
      _checkMobileDataPrompt();
    } catch (e) {
      debugPrint('❌ Error setting up listener: $e');
    }
  }

  /// Check if mobile data prompt should be shown
  void _checkMobileDataPrompt() {
    if (!mounted) {
      debugPrint('🎯 Widget not mounted, skipping check');
      return;
    }
    
    debugPrint('🎯 Checking if prompt should be shown');
    debugPrint('🎯 showMobileDataPrompt = ${_settingsProvider.showMobileDataPrompt}');
    
    if (_settingsProvider.showMobileDataPrompt) {
      debugPrint('🎯 Showing mobile data prompt dialog');
      _showMobileDataPromptDialog();
    }
  }

  /// Show the mobile data prompt dialog
  void _showMobileDataPromptDialog() {
    if (!mounted) {
      debugPrint('❌ Widget not mounted, cannot show dialog');
      return;
    }
    
    debugPrint('💬 Creating and showing MobileDataPromptDialog');
    
    showDialog(
      context: context,
      barrierDismissible: false,
      builder: (dialogContext) => MobileDataPromptDialog(
        onEnableDataSaver: () async {
          debugPrint('✅ User selected: Enable Data Saver');
          if (mounted) {
            await _settingsProvider.enableDataSaverFromPrompt();
            if (mounted) {
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(
                  content: Text('✅ Data Saver Mode enabled successfully!'),
                  duration: Duration(seconds: 2),
                  backgroundColor: Colors.green,
                ),
              );
            }
          }
        },
        onDecline: () async {
          debugPrint('❌ User selected: Not Now');
          if (mounted) {
            await _settingsProvider.declineMobileDataPrompt();
          }
        },
        onDontAskAgain: () async {
          debugPrint('⏰ User selected: Don\'t ask for 24 hours');
          if (mounted) {
            await _settingsProvider.dontAskAgainMobileDataPrompt();
          }
        },
      ),
    ).then((_) {
      // Dialog closed
      debugPrint('💬 Dialog closed');
    });
  }

  @override
  void dispose() {
    try {
      if (_listenerSetup) {
        debugPrint('🎯 Removing listener from SettingsProvider');
        _settingsProvider.removeListener(_checkMobileDataPrompt);
      }
    } catch (e) {
      debugPrint('Error removing listener: $e');
    }
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final systemConditions = context.watch<SystemConditionsProvider>();
    
    return MaterialApp(
      title: 'MyMeds',
      theme: systemConditions.isLowPowerMode 
          ? AppTheme.getLowPowerTheme(false)
          : AppTheme.lightTheme,
      darkTheme: systemConditions.isLowPowerMode 
          ? AppTheme.getLowPowerTheme(true)
          : AppTheme.darkTheme,
      themeMode: systemConditions.themeMode,
      home: const AuthWrapper(), // Use AuthWrapper to handle initial route
      onGenerateRoute: AppRouter.generateRoute,
      debugShowCheckedModeBanner: false,
    );
  }
}
